### ISSUE TITLE
USB enumeration problem and compilation problem with keyberon:master

### ISSUE THREAD

**Issue by mryndzionek** [TeXitoi/keyberon-grid#1]
Current `master` builds, but after flashing to bluepill there are problems with USB enumeration. Probably same problem as in [here](https://github.com/TeXitoi/keyseebee/issues/8). If I switch to keyberon:master it doesn't compile:
```
error: could not compile `keyberon-grid`

To learn more, run the command again with --verbose.
error: Failed to parse crate metadata
```
Verbose doesn't provide more details. I'm willing to dig deeper, but I need a way of getting more debug output.

**Comment by TeXitoi** [comment]
Keyberon0.2 is a breaking change version. You can look at the readme for the changes. keyberon-f4 use master, you can take inspiration.

Another workaround is using an older toolchain.

Sorry, I didn't find the time to finish the 0.2 version for the moment.

**Comment by mryndzionek** [comment]
The main problem I have is that `cargo` returns just `error: could not compile 'keyberon-grid'`. Is there a way to get full error message, with line numbers etc? I see that for example `const CUT: Action` -> `const CUT: Action<()>`, but without detailed compilation error messages it's very difficult to make the adjustments.

**Comment by mryndzionek** [comment]
Hey, I just wanted to let you know that I managed to build working configuration for my Blue Pill based, Atreus-like keyboard. Latest version of keyberon + probe-rs + defmt. Works flawlessly. The code is [here](https://github.com/mryndzionek/keyberon-atreus/blob/main/src/bin/keyboard.rs). Sorry for the stupid questions. I'm still learning Rust and the tooling.

**Comment by TeXitoi** [comment]
Great!
